services:
  replica_key:
    image: bash:5.3.9
    entrypoint:
      - bash
      - -c
      - |
        apk update && apk add openssl
        echo "Generating replica key..."
        openssl rand -base64 756 > /data/custom.replica.key
        chmod 400 /data/custom.replica.key
        chown 999:999 /data/custom.replica.key
        sleep 30
        echo "Replica key generated"
    volumes:
      - mongodb_data:/data
    deploy:
      restart_policy:
        condition: no

  mzinga:
    image: newesissrl.azurecr.io/mzinga/payload/gh/backoffice:0.10.3
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    volumes:
      - mzinga_data:/app/${TENANT:-local}
    depends_on:
      - database
      - messagebus
      - cache
    environment:
      - MONGODB_URI=mongodb://${MONGO_ROOTUSER:-admin}:${MONGO_ROOTPASSWORD:-admin}@database:${MONGO_PORT:-27017}/app?authSource=admin&directConnection=true
      - PAYLOAD_SECRET=${PAYLOAD_SECRET:-secret_key}
      - PORT=${PORT:-3000}
      - DISABLE_TRACING=${DISABLE_TRACING:-0}
      - PAYLOAD_PUBLIC_ENABLE_ZITADEL_PLUGIN=false
      - RABBITMQ_URL=amqp://${RABBITMQ_USER:-guest}:${RABBITMQ_PASSWORD:-guest}@messagebus:${RABBITMQ_PORT:-5672}/
      - TENANT=${TENANT:-local}
      - ENV=prod
      - PAYLOAD_PUBLIC_SERVER_URL=${PAYLOAD_PUBLIC_SERVER_URL:-http://localhost:3000}
      - PAYLOAD_PUBLIC_CONFIG_SERVER_URL=${PAYLOAD_PUBLIC_SERVER_URL:-http://localhost:3000}
      - PAYLOAD_PUBLIC_DISABLED_ENTITIES_SLUGS=$PAYLOAD_PUBLIC_DISABLED_ENTITIES_SLUGS
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-http://jaeger:4318}
      - OTEL_CONSOLE_EXPORTER=1
      - JSON_LIMITS_SIZE=${JSON_LIMITS_SIZE:-20mb}
      - REDIS_URI=${REDIS_URI:-redis://cache:6379}
      - PAYLOAD_PUBLIC_ENABLE_CACHE_PLUGIN=${PAYLOAD_PUBLIC_ENABLE_CACHE_PLUGIN:-true}
      - HOOKSURL_TEAMS_FIELD_DESCRIPTION_AFTERCHANGE=http://webhook-subscriber:4000/webhook
      - HOOKSURL_PLAYERS_AFTERCHANGE=rabbitmq
      - CORS_CONFIGS=*
    deploy:
      replicas: ${MZINGA_DOCKER_COMPOSE_REPLICAS:-1}
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  database:
    image: percona/percona-server-mongodb:8.0.21-9
    depends_on:
      - replica_key
    ports:
      - ${MONGO_PORT:-27017}:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOTUSER:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOTPASSWORD:-admin}
    command:
      [
        "--replSet",
        "rs0",
        "--bind_ip_all",
        "--storageEngine",
        "wiredTiger",
        "--keyFile",
        "/data/db/custom.replica.key",
      ]
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'$MONGO_HOST:${MONGO_PORT:-27017}'}]}) }" | mongosh -u ${MONGO_ROOTUSER:-admin} -p ${MONGO_ROOTPASSWORD:-admin} --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
  messagebus:
    image: rabbitmq:4.3.0-management-alpine
    hostname: rabbitmq
    ports:
      - ${RABBITMQ_PORT:-5672}:5672
      - ${RABBITMQ_PORT_UI:-15672}:15672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 5s
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-guest}
  cache:
    image: redis:8.6.3-alpine
    ports:
      - ${REDIS_PORT:-6379}:6379
    deploy:
      replicas: ${REDIS_REPLICAS:-1}
  ce-enabler:
    image: bash:latest
    volumes:
      - ./compose-scripts:/scripts
      - mzinga_data:/app/${TENANT:-local}
    command: ["/scripts/ce-enabler.sh"]
    environment:
      - TENANT=${TENANT:-local}
    deploy:
      replicas: ${MZINGA_DOCKER_COMPOSE_REPLICAS:-1}
  webhook-subscriber:
    build:
      context: ./examples/webhook-subscriber
    ports:
      - "4000:4000"
    volumes:
      - ./examples/webhook-subscriber:/app
      - /app/node_modules
  servicebus-subscriber:
    build:
      context: ./examples/servicebus-subscriber
    depends_on:
      messagebus:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=amqp://guest:guest@messagebus:5672/
      - ROUTING_KEY=HOOKSURL_PLAYERS_AFTERCHANGE
      - EXCHANGE_NAME=mzinga_events

    volumes:
      - ./examples/servicebus-subscriber:/app
      - /app/node_modules

  jaeger:
    image: jaegertracing/all-in-one:latest
    hostname: jaeger
    ports:
      - "6831:6831/udp" # UDP port for Jaeger agent
      - "16686:16686" # Web UI
      - "14268:14268" # HTTP port for spans
      - "4317:4317"
      - "4318:4318"
    deploy:
      replicas: ${JAEGER_REPLICAS:-1}

  collector:
    container_name: collector
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./o11y-config/otel-collector.yml:/etc/otelcol-contrib/otel-collector.yml
    command:
      - --config=/etc/otelcol-contrib/otel-collector.yml
    restart: always
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
    deploy:
      replicas: ${GRAFANA_REPLICAS:-0}

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    env_file:
      - .env
    volumes:
      - ./o11y-config/prometheus.yml:/etc/prometheus/prometheus-env.yml
      - ./o11y-config/replace-env.sh:/usr/local/bin/replace_env.sh
      - prometheusdata:/prometheus
    entrypoint: /bin/sh
    command: >
      -c "chmod +x /usr/local/bin/replace_env.sh &&
            /usr/local/bin/replace_env.sh /etc/prometheus/prometheus-env.yml /etc/prometheus/prometheus.yml &&
            /bin/prometheus --config.file=/etc/prometheus/prometheus.yml --web.enable-remote-write-receiver --web.enable-otlp-receiver --enable-feature=exemplar-storage --storage.tsdb.retention.time=5d"
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      - collector
    deploy:
      replicas: ${GRAFANA_REPLICAS:-0}

  loki:
    container_name: loki
    restart: always
    image: grafana/loki:latest
    volumes:
      - ./o11y-config/loki-config.yml:/etc/loki/local-config.yaml
      - lokidata:/loki
    ports:
      - "3100:3100"
    depends_on:
      - collector
    deploy:
      replicas: ${GRAFANA_REPLICAS:-0}

  tempo:
    container_name: tempo
    restart: always
    image: grafana/tempo:latest
    volumes:
      - ./o11y-config/tempo.yml:/etc/tempo.yml
      - tempodata:/var/tempo
    command:
      - -config.file=/etc/tempo.yml
    ports:
      - "3200:3200" # tempo
    deploy:
      replicas: ${GRAFANA_REPLICAS:-0}

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    volumes:
      - ./o11y-config/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./o11y-config/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./o11y-config/grafana/dashboards/:/etc/grafana/provisioning/dashboards/json
      - grafanadata:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "8080:3000"
    deploy:
      replicas: ${GRAFANA_REPLICAS:-0}

  redpanda:
    image: redpandadata/redpanda:latest
    ports:
      - "9092:9092" # Kafka API for clients
    command: >
      redpanda start --overprovisioned
      --mode=dev-container
      --kafka-addr=PLAINTEXT://0.0.0.0:9092
      --advertise-kafka-addr=PLAINTEXT://redpanda:9092
    deploy:
      replicas: ${GRAFANA_REPLICAS:-0}

  mongo-exporter:
    image: "percona/mongodb_exporter:2.37"
    environment:
      - MONGODB_URI=mongodb://${MONGO_ROOTUSER:-admin}:${MONGO_ROOTPASSWORD:-admin}@database:27017/app?authSource=admin&directConnection=true
    command: ["--collect-all", "--compatible-mode", "--discovering-mode"]
    ports:
      - 9216:9216
    deploy:
      replicas: ${GRAFANA_REPLICAS:-0}

volumes:
  mongodb_data:
    driver: local
    driver_opts:
      type: ${DRIVER_OPTS_TYPE}
      o: ${DRIVER_OPTS_OPTIONS}
      device: ${DRIVER_OPTS_DEVICE}/database
  mzinga_data:
    driver: local
    driver_opts:
      type: ${DRIVER_OPTS_TYPE}
      o: ${DRIVER_OPTS_OPTIONS}
      device: ${DRIVER_OPTS_DEVICE}/mzinga
  rabbitmq_data:
    driver: local
    driver_opts:
      type: ${DRIVER_OPTS_TYPE}
      o: ${DRIVER_OPTS_OPTIONS}
      device: ${DRIVER_OPTS_DEVICE}/messagebus
  grafanadata:
  prometheusdata:
  lokidata:
  tempodata:
